name: basic
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter


  go_router: ^14.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  just_audio: ^0.9.41
  audioplayers: ^6.1.0
  simple_ripple_animation: ^0.0.9


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/board.jpg
    - assets/images/dice/
    - assets/images/
    - assets/images/crown/
    - assets/music/
    - assets/sounds/
    - assets/sounds/move.wav
    - assets/sounds/kill.wav
    - assets/sounds/roll_the_dice.mp3
    - assets/sounds/level-up.mp3
    - assets/icon/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo_foreground.png"
